[package]
name = "iceberg_rust_sinatra"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
rutie = { version = "0.6.0-rc.2" }
iceberg-rust = "0.3.0"
tokio = { version = "1", features = ["full"] }
anyhow = "1.0"
serde_json = "1.0"
